version: '3.3'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_user
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    secrets:
      - db_user
      - db_password
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER_FILE: /run/secrets/db_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password

volumes:
    db_data: {}

secrets:
  db_user:
    file: ./db_user.txt
  db_password:
    file: ./db_password.txt
